# NUMPY- NUMERICAL PHYTON

In [ ]:
Packages in python- They are libray purposely built to provide solutions to a specific problems

NUMPY- NUMERICAL PYTHON - it is purposely built on mathematics operation
PANDAS - It is purposely built to perform data manipulation
MATPLOT/ SEABURN/ PLOCKTLY - It is bulit to perform data visualization
SCIKIT/SCILEARN - it is built to perform machine learning applications
KERAS/ PYTOCH - It is built to perform deep learning applications


In [4]:
import numpy

In [3]:
import numpy as np

# CREATING NUMPY ARRAY

In [ ]:
State the difference between list and array

In [ ]:
np.array(object,ndmin,dtype)

1. from an existing object
Array can be creared as python object such as disc,list, tuple and set

In [2]:
# creating one dimensional array from one dimensional list
import numpy as np
list1 = [1,4,5,6,1,7]
arry1 = np.array(list1)
arry1

array([1, 4, 5, 6, 1, 7])

In [6]:
# creating two dimensional array from two dimensional list
list2 =[[5,7,0,10,12,12,45  ]]
arry2 = np.array(list2)
arry2

array([[ 5,  7,  0, 10, 12, 12, 45]])

In [7]:
# To check the dimension of array
arry2.ndim

2

In [10]:
# creating three dimensional from one dimensional list
list2 =[[5,7,0,10,12,12,45  ]]
arry3 = np.array(list2, ndmin=3)
arry3

array([[[ 5,  7,  0, 10, 12, 12, 45]]])

In [13]:
# creating three dimensional from one dimensional list
list2 =[5,7,0,10,12,12,45  ]
arry3 = np.array(list2, ndmin=3, dtype="complex")
arry3

array([[[ 5.+0.j,  7.+0.j,  0.+0.j, 10.+0.j, 12.+0.j, 12.+0.j, 45.+0.j]]])

In [6]:
# creating three dimensional from one dimensional list
list2 =[5,7,0,10,12,12,45  ]
arry3 = np.array(list2, ndmin=3, dtype="float")
arry3

array([[[ 5.,  7.,  0., 10., 12., 12., 45.]]])

In [7]:
# creating three dimensional from one dimensional list
list2 =[5,7,0,10,12,12,45  ]
arry3 = np.array(list2, ndmin=3, dtype="int")
arry3

array([[[ 5,  7,  0, 10, 12, 12, 45]]])

In [8]:
# creating three dimensional from one dimensional list
list2 =[5,7,0,10,12,12,45  ]
arry3 = np.array(list2, ndmin=3, dtype="object")
arry3

array([[[5, 7, 0, 10, 12, 12, 45]]], dtype=object)

Exercise
Create numpy three dimensionas and integer data type from the list below [2,4,5,22,8,54,22]

list2 =[2,4,5,22,8,54,22  ]
arry3= np.array(list2, ndmin=3, dtype="int")
arry3

In [34]:
list2 =[2,4,5,22,8,54,22  ]
arry3= np.array(list2, ndmin=3, dtype="int")
arry3

array([[[ 2,  4,  5, 22,  8, 54, 22]]])

In [15]:
# 4 Numpy - Array from numerical ranges
# `numpy.arrange(start, stop, dtype)`
np.arange(0, 11)

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10])

In [17]:
np.arange(0,11,2)

array([ 0,  2,  4,  6,  8, 10])

In [22]:
# creating array using linspace
#`numpy.linspace(start,stop, num,endpoint, dtype)`
np.linspace(10, 50, 5, endpoint=True)

array([10., 20., 30., 40., 50.])

In [23]:
# creating array using linspace
#`numpy.linspace(start,stop, num,endpoint, dtype)`
np.linspace(10, 50, 50, endpoint=True)

array([10.        , 10.81632653, 11.63265306, 12.44897959, 13.26530612,
       14.08163265, 14.89795918, 15.71428571, 16.53061224, 17.34693878,
       18.16326531, 18.97959184, 19.79591837, 20.6122449 , 21.42857143,
       22.24489796, 23.06122449, 23.87755102, 24.69387755, 25.51020408,
       26.32653061, 27.14285714, 27.95918367, 28.7755102 , 29.59183673,
       30.40816327, 31.2244898 , 32.04081633, 32.85714286, 33.67346939,
       34.48979592, 35.30612245, 36.12244898, 36.93877551, 37.75510204,
       38.57142857, 39.3877551 , 40.20408163, 41.02040816, 41.83673469,
       42.65306122, 43.46938776, 44.28571429, 45.10204082, 45.91836735,
       46.73469388, 47.55102041, 48.36734694, 49.18367347, 50.        ])

In [24]:
# creating array using linspace
#`numpy.linspace(start,stop, num,endpoint, dtype)`
np.linspace(10, 50, 50, endpoint=False)

array([10. , 10.8, 11.6, 12.4, 13.2, 14. , 14.8, 15.6, 16.4, 17.2, 18. ,
       18.8, 19.6, 20.4, 21.2, 22. , 22.8, 23.6, 24.4, 25.2, 26. , 26.8,
       27.6, 28.4, 29.2, 30. , 30.8, 31.6, 32.4, 33.2, 34. , 34.8, 35.6,
       36.4, 37.2, 38. , 38.8, 39.6, 40.4, 41.2, 42. , 42.8, 43.6, 44.4,
       45.2, 46. , 46.8, 47.6, 48.4, 49.2])

In [25]:
# creating array using linspace
#`numpy.linspace(start,stop, num,endpoint, dtype)`
np.linspace(10, 50, 4, endpoint=False)

array([10., 20., 30., 40.])

create numpy array of object data type containing just 8 element within 10 and 90. endpoint should be excluded

create numpy of int data type fro  7 to 70 with interval of 8

In [26]:
np.linspace(10,90,8, endpoint=False, dtype=object)

array([10.0, 20.0, 30.0, 40.0, 50.0, 60.0, 70.0, 80.0], dtype=object)

In [27]:
np.arange(7, 71, 8, dtype=int)

array([ 7, 15, 23, 31, 39, 47, 55, 63])

In [ ]:
Attribute of Array:
shape- number of element in each of the dimension

In [31]:
# how to check shape in arr
arry5 =np.array( [ [[2, 5],
           [8,3],
           [6,4]],
        
           [[1,6],
            [4,0],
            [4,5]]] )

arry5.shape
        

(2, 3, 2)

In [32]:
arry6=np.arange(7, 71, 8, dtype=int)
arry6.shape

(8,)

In [35]:
arry7=np.array([[2,6,7,8],
                [2,6,7,8],
                [2,6,7,8],
                [2,6,7,8],
                [2,6,7,8]])
                  
arry7.shape

(5, 4)

In [36]:
# reshaping the shape of array **`2 Reshape()`**
arry8=np.arange(7, 71,4, dtype=int)
print(arry8)
arry8.shape

[ 7 11 15 19 23 27 31 35 39 43 47 51 55 59 63 67]


(16,)

In [38]:
arry_reshape=arry8.reshape(4,4,1)
arry_reshape.shape

(4, 4, 1)

In [39]:
arry_reshape=arry8.reshape(16,1)
arry_reshape.shape

(16, 1)

In [44]:
# set base of log space to 2
import numpy as np

a=np.linspace(1,10, num=10)
print(a)
a.shape

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


(10,)

In [45]:
# reshape array in two dimension array
a=a.reshape(2, 5)
print(a)
print( "the shape of array a after reshaping", a.shape)

[[ 1.  2.  3.  4.  5.]
 [ 6.  7.  8.  9. 10.]]
the shape of array a after reshaping (2, 5)


In [ ]:
the result above is the two dimensional array having one element in one dimension and five element in the second dimension

In [ ]:
the above indicates there are two elements in the first dimension array

# Numpy Indexing and Slicing
contents of ndarray objects can be accessed and modified by indexing and slicing

In [ ]:
** Indexing**

In [47]:
# slice index item
import numpy as np
a = np.arange(10,40,4)
print(a)

[10 14 18 22 26 30 34 38]


In [48]:
# return element at index five
b =a[5]
print ("print tje element at index 5 is", b)

print tje element at index 5 is 30


In [49]:
import numpy as np

# return the second element of array below
a = np.array([ [1,2,3] ,[3,4,5], [7,5,6] ])
print(a[1])

[3 4 5]


# Slicing

In [51]:
import numpy as np
# return element 7 8 9 10 11 12 from below array
a =np.arange(3,17)
print(a)
a[4:10]

[ 3  4  5  6  7  8  9 10 11 12 13 14 15 16]


array([ 7,  8,  9, 10, 11, 12])

In [52]:
# slice items starting from index
import numpy as np
a = np. arange(10)
print (a, '\n') # '\n' indicate next line
# started from index two to end of the array
print(a[2:])

[0 1 2 3 4 5 6 7 8 9] 

[2 3 4 5 6 7 8 9]


#### we slice through the array a by starting at index2 and stop at index 5

# Boolean Array Indexing
#### This type of advanced indexing is used when the resultant object is meant to be result of Boolean operations, such as comparison operators.

In [53]:
import numpy as np
x= np. array([[ 0,1,2], [3,4,5],[6,7,8], [9,10,11] ])
print('Our array is:', '\n', x, '\n')

Our array is: 
 [[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]] 



In [54]:
# filter out element greater than 5
x[x >=5] # this will return element equal or greater than five

array([ 5,  6,  7,  8,  9, 10, 11])

In [57]:
# filter out the elements  array that are not equals to three
a=np.array([[1,2,3],[3,4,5],[4,5,6] ])
a[a==3]

array([3, 3])

# Changing the dimension of the array

In [59]:
np.flatten()
Return a copy of array collapsed in one dimension

SyntaxError: invalid syntax (3377996320.py, line 2)

In [61]:
import numpy as np
a =np.array([[[[0.0,0.0,0.0],[10.0,10.0,10.0],[20.0,20.0,20.0],[30.0,30.0,30.0]]]])
print(a)
print("Dimensional of array before flatten", a.ndim)

[[[[ 0.  0.  0.]
   [10. 10. 10.]
   [20. 20. 20.]
   [30. 30. 30.]]]]
Dimensional of array before flatten 4


In [62]:
a.shape

(1, 1, 4, 3)

In [63]:
b=a.flatten()
print(b)
print("\nDimensional of array after flatten", b.ndim )

[ 0.  0.  0. 10. 10. 10. 20. 20. 20. 30. 30. 30.]

Dimensional of array after flatten 1


# Append
To add elemt to the end of existing array


In [64]:
import numpy as np
#add [1,2,3] to array a
a=[[4,5,6], [7,8,9]]
b=[1,2,3]
c=np.append(a,b)# adding two list and converting to numpy array
c

array([4, 5, 6, 7, 8, 9, 1, 2, 3])